import { notFound } from 'next/navigation'
import Link from 'next/link'
import { requirePermission } from '@/lib/auth'
import { queryOne, query } from '@/lib/db'
import { Card, PageHeader, Th, Td, StatusBadge } from '@/components/admin/ui'

export default async function CustomerDetailPage({ params }: { params: Promise<{ id: string }> }) {
  await requirePermission('customers.view')
  const { id } = await params
  const customer = await queryOne<{ id: string; name: string; email: string; phone: string | null; email_verified: boolean; birthday: string | null; anniversary: string | null; created_at: string }>('SELECT id,name,email,phone,email_verified,birthday::text,anniversary::text,created_at::text FROM users WHERE id=$1 AND role=\'CUSTOMER\'', [id])
  if (!customer) notFound()
  const [orders, reservations, reviews, loyalty] = await Promise.all([
    query<{ reference: string; total: string; status: string; created_at: string; items: string }>(`SELECT o.reference,o.total::text,o.status,o.created_at::text,coalesce(string_agg(oi.quantity || ' × ' || oi.name, ', '),'') AS items FROM orders o LEFT JOIN order_items oi ON oi.order_id=o.id WHERE o.user_id=$1 GROUP BY o.id ORDER BY o.created_at DESC LIMIT 50`, [id]),
    query<{ reference: string | null; reserved_date: string; reserved_time: string; guests: number; status: string }>('SELECT reference,reserved_date::text,reserved_time,guests,status FROM reservations WHERE user_id=$1 ORDER BY reserved_date DESC LIMIT 30', [id]),
    query<{ rating: number; title: string | null; body: string; status: string; created_at: string }>('SELECT rating,title,body,status,created_at::text FROM reviews WHERE user_id=$1 ORDER BY created_at DESC', [id]),
    queryOne<{ points_balance: number; lifetime_points: number }>('SELECT points_balance,lifetime_points FROM loyalty_accounts WHERE user_id=$1', [id]),
  ])
  return <main className="space-y-6"><PageHeader title={customer.name || 'Customer'} subtitle={customer.email} action={<Link href="/admin/customers" className="btn-outline-gold rounded-lg px-4 py-2 text-xs uppercase tracking-widest">Back to CRM</Link>} />
    <div className="grid gap-4 md:grid-cols-4"><Card><p className="text-xs text-muted-foreground">Email</p><p className="mt-2 text-sm text-beige">{customer.email}</p><StatusBadge label={customer.email_verified ? 'Verified' : 'Unverified'} tone={customer.email_verified ? 'green' : 'yellow'} /></Card><Card><p className="text-xs text-muted-foreground">Phone</p><p className="mt-2 text-sm text-beige">{customer.phone || 'Not set'}</p></Card><Card><p className="text-xs text-muted-foreground">Loyalty balance</p><p className="mt-2 font-serif text-2xl text-gold">{loyalty?.points_balance ?? 0}</p></Card><Card><p className="text-xs text-muted-foreground">Member since</p><p className="mt-2 text-sm text-beige">{new Date(customer.created_at).toLocaleDateString('en-IN')}</p></Card></div>
    <Card title="Order history" className="overflow-hidden p-0"><div className="overflow-x-auto"><table className="w-full min-w-[700px]"><thead><tr><Th>Reference</Th><Th>Items</Th><Th>Status</Th><Th align="right">Total</Th><Th>Date</Th></tr></thead><tbody>{orders.map((o) => <tr key={o.reference} className="border-t border-border/70"><Td><Link className="text-gold hover:underline" href={`/admin/orders/${o.reference}`}>{o.reference}</Link></Td><Td className="text-xs text-muted-foreground">{o.items}</Td><Td><StatusBadge label={o.status} /></Td><Td align="right">Rs. {Number(o.total).toLocaleString('en-IN')}</Td><Td>{new Date(o.created_at).toLocaleDateString('en-IN')}</Td></tr>)}</tbody></table></div>{orders.length===0 && <p className="p-8 text-sm text-muted-foreground">No orders yet.</p>}</Card>
    <div className="grid gap-6 lg:grid-cols-2"><Card title="Reservations"><div className="space-y-3">{reservations.map((r) => <div key={r.reference ?? `${r.reserved_date}-${r.reserved_time}`} className="flex items-center justify-between border-b border-border/70 pb-3 text-sm"><span>{new Date(r.reserved_date).toLocaleDateString('en-IN')} · {r.reserved_time}<span className="block text-xs text-muted-foreground">{r.guests} guests · {r.reference || 'No reference'}</span></span><StatusBadge label={r.status} /></div>)}{reservations.length===0 && <p className="text-sm text-muted-foreground">No reservations.</p>}</div></Card><Card title="Reviews"><div className="space-y-3">{reviews.map((r) => <div key={r.created_at} className="border-b border-border/70 pb-3"><div className="flex justify-between"><span className="text-gold">{'★'.repeat(r.rating)}<span className="text-muted-foreground">{'★'.repeat(5-r.rating)}</span></span><StatusBadge label={r.status} /></div><p className="mt-1 text-sm text-beige">{r.title || r.body}</p></div>)}{reviews.length===0 && <p className="text-sm text-muted-foreground">No reviews.</p>}</div></Card></div>
  </main>
}
